#Crafter Presets Settings
#Mon Sep 21 02:18:31 CEST 2026
autoExit=false
autoExitThreshold=3
autoLoad=false
customClickSound=true
lastSeenUpdateVersion=20260430-215627
outlineColor=FF00FF00
showHoverPreview=true
showOutlines=false
silentMode=false
singlePresetMode=false
watermarkDismissedVersion=
